version: '3.7'
services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=0cd35d7asdERgfd4354765886543ce71
    ports:
      - "3306:3306"
    expose:
      - "3306"      
    volumes:
      - db_data:/var/lib/mysql
